<?xml version="1.0"?>
<package format="3">
  <name>robot_capability_api</name>
  <version>0.3.0</version>
  <description>Navigation and manipulation capability port interfaces.</description>
  <maintainer email="stereo.39bouvier@icloud.com">stereo</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>robot_core_api</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
